# Utilizar la imagen oficial de Nginx
FROM nginx:alpine

# Copiar el archivo index.html al directorio por defecto de Nginx
COPY index.html /usr/share/nginx/html/index.html

# No es necesario definir CMD porque la imagen de Nginx ya tiene un proceso por defecto